baseurl: '/'
permalink: pretty
title: 'Dynamics Monster'

logo:
  mobile: "images/logo/dynamics_monster_logo_mobile.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/dynamics_monster_logo.png"
  desktop_height: "32px"
  desktop_width: "120px"

collections:
  services:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

feed:
  path: /blog/feed.atom

sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
